import { Link } from 'react-router'
import { ArrowUpRight, ChartColumn, CirclePlus, Ticket, Wallet } from 'lucide-react'
import styles from './OrganizerDashboard.module.css'

export function OrganizerDashboard() {
  return <div className={styles.dashboard}>
    <div className={styles.heading}><div><span className={styles.eyebrow}><i /> KHÔNG GIAN BAN TỔ CHỨC</span><h1>Tổng quan ban tổ chức</h1><p>Chào mừng bạn trở lại. Bắt đầu hành trình sự kiện tiếp theo của bạn.</p></div><Link className={styles.primary} to="events/new/details"><CirclePlus size={18} /> Tạo sự kiện mới</Link></div>
    <p className={styles.demo}>Giao diện minh họa — các số liệu và chức năng quản lý sẽ được kết nối sau.</p>
    <div className={styles.stats}>
      {[{ title: 'TỔNG DOANH THU SỰ KIỆN', value: '4.820.000.000', note: 'VNĐ', icon: Wallet }, { title: 'TỔNG SỐ SỰ KIỆN', value: '12', note: 'sự kiện', icon: Ticket }, { title: 'TỔNG SỐ VÉ ĐÃ BÁN', value: '18.450', note: 'vé thành công', icon: ChartColumn }, { title: 'SỐ DƯ KHẢ DỤNG', value: '1.450.000.000', note: 'VNĐ', icon: Wallet }].map(({ title, value, note, icon: Icon }) => <article className={styles.stat} key={title}><div><span>{title}</span><Icon size={24} /></div><strong>{value}</strong><p>{note}</p><small><ArrowUpRight size={14} /> Dữ liệu minh họa</small></article>)}
    </div>
    <div className={styles.charts}><article className={styles.card}><span className={styles.eyebrow}>CHỈ SỐ TÀI CHÍNH</span><h2>Doanh thu bán vé theo thời gian</h2><div className={styles.chartNote}><span /> Doanh thu thực nhận <small>Dữ liệu minh họa</small></div><svg className={styles.lineChart} viewBox="0 0 650 230" role="img" aria-label="Biểu đồ doanh thu minh họa tăng qua sáu tháng"><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#24bf76" stopOpacity=".3" /><stop offset="100%" stopColor="#24bf76" stopOpacity="0" /></linearGradient></defs>{[40, 90, 140, 190].map(y => <line key={y} x1="5" y1={y} x2="645" y2={y} stroke="#e2e7e5" strokeDasharray="4 4" />)}<path d="M5 205 C90 188 100 162 155 158 S235 163 275 128 S365 122 395 80 S490 95 525 58 S600 26 645 14 L645 225 L5 225Z" fill="url(#revenue-fill)" /><path d="M5 205 C90 188 100 162 155 158 S235 163 275 128 S365 122 395 80 S490 95 525 58 S600 26 645 14" fill="none" stroke="#24bf76" strokeWidth="4" /></svg><div className={styles.months}>{['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6'].map(month => <span key={month}>{month}</span>)}</div></article>
      <article className={styles.card}><span className={styles.eyebrow}>PHÂN BỔ SỰ KIỆN</span><h2>Trạng thái & tỷ lệ bán vé</h2><div className={styles.percent}><small>Tỷ lệ hoàn thành sự kiện</small><strong>95,2%</strong></div>{[{ text: 'Đang diễn ra', count: 3, color: '#24bf76' }, { text: 'Đã kết thúc', count: 6, color: '#28b5ef' }, { text: 'Chờ duyệt', count: 2, color: '#ff6565' }, { text: 'Đã hủy', count: 1, color: '#a0aec0' }].map(item => <div className={styles.progress} key={item.text}><p><span>{item.text}</span><strong>{item.count} sự kiện</strong></p><div><i style={{ width: `${item.count / 12 * 100}%`, background: item.color }} /></div></div>)}</article></div>
    <article className={styles.startCard}><div className={styles.startIcon}><Ticket size={30} /></div><div><h2>Sự kiện tiếp theo bắt đầu từ đây</h2><p>Thiết lập thông tin, thêm khách mời và các loại vé. Gửi hồ sơ để Admin xét duyệt.</p></div><Link className={styles.primary} to="events/new/details">Bắt đầu tạo sự kiện <ArrowUpRight size={18} /></Link></article>
  </div>
}
